"""Criação inicial das tabelas

Revision ID: 8092829b759f
Revises: 
Create Date: 2025-09-21 23:27:02.847641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8092829b759f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treinamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_treinamento', sa.String(length=150), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('instrutor_sugerido', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=50), nullable=True),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('treinamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['treinamento_id'], ['treinamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    op.drop_table('turmas')
    op.drop_table('treinamentos')
    # ### end Alembic commands ###
